apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: ${NAMESPACE}
  labels:
    app: etcd
spec:
  clusterIP: None  # Headless service for direct pod DNS
  selector:
    app: etcd
  ports:
    - port: 2379  # Client port
      name: client
    - port: 2380  # Peer port
      name: peer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ${NAMESPACE}
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.7
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
          command:
            - /usr/local/bin/etcd
          args:
            - --data-dir=/etcd-data
            - --name=$(POD_NAME)
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd:2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd:2379
            - --initial-cluster=etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster-1
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
