apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${NAMESPACE}
spec:
  clusterIP: None
  selector:
    app: patroni
  ports:
    - name: postgres
      port: 5432
    - name: api
      port: 8008
