apiVersion: v1
kind: Pod
metadata:
  name: browseterm-pg
  namespace: ${NAMESPACE}
  labels:
    app: browseterm-pg
spec:
  containers:
  - name: postgres
    image: postgres:15
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: ${POSTGRES_USER}
    - name: POSTGRES_PASSWORD
      value: ${POSTGRES_PASSWORD}
    - name: POSTGRES_DB
      value: ${POSTGRES_DB}
    volumeMounts:
    - name: pgdata
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: pgdata
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: browseterm-pg-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: browseterm-pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-password
  namespace: ${NAMESPACE}
type: Opaque
data:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BASE64}